<?php
$gradients = array(
    "blue-to-green",
    "blue-to-orange",
    "blue-to-pink",
    "blue-to-purple",
    "green-to-blue",
    "green-to-orange",
    "green-to-pink",
    "green-to-purple",
    "orange-to-blue",
    "orange-to-green",
    "orange-to-pink",
    "orange-to-purple",
    "pink-to-blue",
    "pink-to-green",
    "pink-to-orange",
    "pink-to-purple",
    "purple-to-blue",
    "purple-to-green",
    "purple-to-orange",
    "purple-to-pink",
);
?>